// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Yd9Xrt2dvpnawKrPy7JicFGB08gKdyU',
    appId: '1:643468228934:web:545b6557291158c3ad4d47',
    messagingSenderId: '643468228934',
    projectId: 'catfeederta',
    authDomain: 'catfeederta.firebaseapp.com',
    databaseURL: 'https://catfeederta-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'catfeederta.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVZjSTDDWtY5uN7ITQ0U4YoGXo9lC2VAQ',
    appId: '1:643468228934:android:1fbd71acc49e8accad4d47',
    messagingSenderId: '643468228934',
    projectId: 'catfeederta',
    databaseURL: 'https://catfeederta-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'catfeederta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQHDdWqSw1lQ3lQa3IOYKnWUXC552ZVBA',
    appId: '1:643468228934:ios:b368ae8e3cb193c1ad4d47',
    messagingSenderId: '643468228934',
    projectId: 'catfeederta',
    databaseURL: 'https://catfeederta-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'catfeederta.appspot.com',
    iosBundleId: 'com.example.catfeederFlutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQHDdWqSw1lQ3lQa3IOYKnWUXC552ZVBA',
    appId: '1:643468228934:ios:263d0276a450e036ad4d47',
    messagingSenderId: '643468228934',
    projectId: 'catfeederta',
    databaseURL: 'https://catfeederta-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'catfeederta.appspot.com',
    iosBundleId: 'com.example.catfeederFlutterapp.RunnerTests',
  );
}
